apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testdocs
  description: Documentation centralisée pour TestDocs
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: team-docs
